"""Full product catalog — 30 Nike-style products with working image URLs."""

def img(photo_id: int) -> str:
    return (
        f"https://images.pexels.com/photos/{photo_id}/"
        f"pexels-photo-{photo_id}.jpeg?auto=compress&w=800"
    )

MEN_SIZES = ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12", "13"]
WOMEN_SIZES = ["5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10"]
KIDS_SIZES = ["10.5C", "11.5C", "12.5C", "13.5C", "1Y", "2Y", "3Y", "4Y", "5Y", "6Y"]
UNISEX_SIZES = ["5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12"]

PRODUCTS = [
    {"name": "Air Jordan 1 Retro High OG", "subtitle": "Men's Shoes", "description": "The Air Jordan 1 Retro High OG brings back the iconic silhouette that started it all.", "price": 180.00, "category": "Jordan", "gender": "men", "color": "Black/White/Red", "image_url": img(2529148), "image_url_2": img(2529156), "sizes": MEN_SIZES, "tags": ["basketball", "iconic"], "sustainability_score": 62, "is_featured": True, "is_new": False},
    {"name": "Nike Air Max 90", "subtitle": "Men's Shoes", "description": "Nothing as legendary. The Nike Air Max 90 stays true to its OG running roots.", "price": 130.00, "category": "Lifestyle", "gender": "men", "color": "White/Black", "image_url": img(1032110), "image_url_2": img(1598505), "sizes": MEN_SIZES, "tags": ["classic", "air max"], "sustainability_score": 58, "is_featured": True, "is_new": False},
    {"name": "Nike Dunk Low", "subtitle": "Women's Shoes", "description": "Created for the hardwood but taken to the streets.", "price": 115.00, "category": "Lifestyle", "gender": "women", "color": "White/Pink", "image_url": img(267301), "image_url_2": img(2529118), "sizes": WOMEN_SIZES, "tags": ["streetwear"], "sustainability_score": 55, "is_featured": True, "is_new": True},
    {"name": "Nike Air Force 1 '07", "subtitle": "Men's Shoes", "description": "Comfortable, durable and timeless. The radiance lives on in the Nike Air Force 1.", "price": 115.00, "category": "Lifestyle", "gender": "men", "color": "White", "image_url": img(1456706), "image_url_2": img(1464625), "sizes": MEN_SIZES, "tags": ["classic"], "sustainability_score": 60, "is_featured": False, "is_new": False},
    {"name": "Nike Air Max 270", "subtitle": "Women's Shoes", "description": "Nike's first lifestyle Air Max brings you style, comfort and big attitude.", "price": 160.00, "category": "Lifestyle", "gender": "women", "color": "Black/White", "image_url": img(298863), "image_url_2": img(336372), "sizes": WOMEN_SIZES, "tags": ["air max"], "sustainability_score": 57, "is_featured": False, "is_new": True},
    {"name": "Nike React Infinity Run Flyknit 3", "subtitle": "Men's Running Shoes", "description": "Made to help reduce injury and keep you on the run.", "price": 160.00, "category": "Running", "gender": "men", "color": "Black/Volt", "image_url": img(643471), "image_url_2": img(631986), "sizes": MEN_SIZES, "tags": ["running", "flyknit"], "sustainability_score": 78, "is_featured": False, "is_new": True},
    {"name": "Nike Pegasus 40", "subtitle": "Women's Running Shoes", "description": "Reliable for road runs from flat streets to challenging hills.", "price": 130.00, "category": "Running", "gender": "women", "color": "White/Pink Blast", "image_url": img(1478442), "image_url_2": img(298845), "sizes": WOMEN_SIZES, "tags": ["running"], "sustainability_score": 74, "is_featured": False, "is_new": False},
    {"name": "Nike Metcon 8", "subtitle": "Men's Training Shoes", "description": "The gold standard for weightlifting — tougher and more stable.", "price": 150.00, "category": "Training", "gender": "men", "color": "Black/White", "image_url": img(2529156), "image_url_2": img(1032110), "sizes": MEN_SIZES, "tags": ["training", "crossfit"], "sustainability_score": 65, "is_featured": False, "is_new": False},
    {"name": "Nike Blazer Mid '77", "subtitle": "Women's Shoes", "description": "A slice of Nike style from the '70s with classic suede and leather.", "price": 100.00, "category": "Lifestyle", "gender": "women", "color": "White/Black", "image_url": img(1598505), "image_url_2": img(267301), "sizes": WOMEN_SIZES, "tags": ["retro"], "sustainability_score": 52, "is_featured": True, "is_new": False},
    {"name": "Nike ZoomX Vaporfly NEXT% 2", "subtitle": "Men's Racing Shoes", "description": "Continue the evolution of speed with a racing shoe for new records.", "price": 250.00, "category": "Running", "gender": "men", "color": "Volt/Black", "image_url": img(1456706), "image_url_2": img(298863), "sizes": MEN_SIZES, "tags": ["racing", "marathon"], "sustainability_score": 70, "is_featured": False, "is_new": True},
    {"name": "Nike Air Max 1", "subtitle": "Unisex Shoes", "description": "Stays true to its OG roots with visible Air cushioning.", "price": 140.00, "category": "Lifestyle", "gender": "unisex", "color": "White/Red", "image_url": img(1464625), "image_url_2": img(336372), "sizes": UNISEX_SIZES, "tags": ["air max", "iconic"], "sustainability_score": 56, "is_featured": True, "is_new": False},
    {"name": "Nike Free Metcon 5", "subtitle": "Women's Training Shoes", "description": "Flexibility of Nike Free meets stability of Metcon.", "price": 120.00, "category": "Training", "gender": "women", "color": "Black/White", "image_url": img(631986), "image_url_2": img(1478442), "sizes": WOMEN_SIZES, "tags": ["training"], "sustainability_score": 68, "is_featured": False, "is_new": False},
    # --- 18 new products ---
    {"name": "Nike Air Max DN", "subtitle": "Men's Shoes", "description": "Dynamic Air unit system delivers unbelievable comfort and style.", "price": 200.00, "category": "Lifestyle", "gender": "men", "color": "Multi-Color", "image_url": img(2529148), "image_url_2": img(643471), "sizes": MEN_SIZES, "tags": ["air max", "innovation"], "sustainability_score": 72, "is_featured": True, "is_new": True},
    {"name": "Nike Sabrina 1", "subtitle": "Women's Basketball Shoes", "description": "Built for shifty guards who need responsive traction and lockdown fit.", "price": 130.00, "category": "Basketball", "gender": "women", "color": "Photon Dust/Pink", "image_url": img(267301), "image_url_2": img(298845), "sizes": WOMEN_SIZES, "tags": ["basketball"], "sustainability_score": 64, "is_featured": True, "is_new": True},
    {"name": "Nike Mercurial Vapor 15", "subtitle": "Men's Soccer Cleats", "description": "Designed for speed with Aerotrak zone for explosive acceleration.", "price": 275.00, "category": "Soccer", "gender": "men", "color": "Volt/Black", "image_url": img(1032110), "image_url_2": img(2529156), "sizes": MEN_SIZES, "tags": ["soccer", "cleats"], "sustainability_score": 61, "is_featured": False, "is_new": True},
    {"name": "Nike Revolution 7", "subtitle": "Kids' Running Shoes", "description": "Soft foam and breathable mesh for all-day play and comfort.", "price": 60.00, "category": "Running", "gender": "kids", "color": "Blue/Orange", "image_url": img(2529118), "image_url_2": img(336372), "sizes": KIDS_SIZES, "tags": ["kids", "running"], "sustainability_score": 80, "is_featured": False, "is_new": True},
    {"name": "Nike Air Max 90 Kids", "subtitle": "Kids' Shoes", "description": "The icon scaled down for the next generation.", "price": 90.00, "category": "Lifestyle", "gender": "kids", "color": "White/Grey", "image_url": img(1598505), "image_url_2": img(2529148), "sizes": KIDS_SIZES, "tags": ["kids", "air max"], "sustainability_score": 75, "is_featured": True, "is_new": False},
    {"name": "Nike ACG Mountain Fly 2", "subtitle": "Men's Trail Shoes", "description": "All Conditions Gear for technical trails and unpredictable terrain.", "price": 180.00, "category": "Trail", "gender": "men", "color": "Olive/Black", "image_url": img(643471), "image_url_2": img(631986), "sizes": MEN_SIZES, "tags": ["trail", "acg"], "sustainability_score": 82, "is_featured": False, "is_new": True},
    {"name": "Nike Cortez", "subtitle": "Unisex Shoes", "description": "The original running shoe that defined West Coast style.", "price": 90.00, "category": "Lifestyle", "gender": "unisex", "color": "White/Red/Blue", "image_url": img(1464625), "image_url_2": img(1032110), "sizes": UNISEX_SIZES, "tags": ["retro", "classic"], "sustainability_score": 54, "is_featured": False, "is_new": False},
    {"name": "Nike Killshot 2", "subtitle": "Men's Shoes", "description": "Retro tennis-inspired design with premium leather upper.", "price": 100.00, "category": "Lifestyle", "gender": "men", "color": "Sail/Midnight Navy", "image_url": img(298863), "image_url_2": img(1456706), "sizes": MEN_SIZES, "tags": ["retro"], "sustainability_score": 53, "is_featured": False, "is_new": False, "is_on_sale": True, "sale_price": 79.00},
    {"name": "Nike Waffle One", "subtitle": "Women's Shoes", "description": "Translucent mesh and suede overlays meet iconic Waffle outsole.", "price": 110.00, "category": "Lifestyle", "gender": "women", "color": "Summit White", "image_url": img(1478442), "image_url_2": img(267301), "sizes": WOMEN_SIZES, "tags": ["lifestyle"], "sustainability_score": 66, "is_featured": False, "is_new": False},
    {"name": "Nike Alphafly 3", "subtitle": "Men's Racing Shoes", "description": "ZoomX foam and Air Zoom pods for marathon-breaking speed.", "price": 285.00, "category": "Running", "gender": "men", "color": "Proto Volt", "image_url": img(2529156), "image_url_2": img(298863), "sizes": MEN_SIZES, "tags": ["racing", "marathon"], "sustainability_score": 71, "is_featured": True, "is_new": True, "is_on_sale": True, "sale_price": 229.00},
    {"name": "Nike Gamma Force", "subtitle": "Women's Shoes", "description": "Chunky '80s basketball aesthetic meets modern comfort.", "price": 100.00, "category": "Lifestyle", "gender": "women", "color": "White/Black", "image_url": img(336372), "image_url_2": img(1598505), "sizes": WOMEN_SIZES, "tags": ["retro"], "sustainability_score": 59, "is_featured": False, "is_new": False, "is_on_sale": True, "sale_price": 75.00},
    {"name": "Nike Invincible 3", "subtitle": "Men's Running Shoes", "description": "Maximum ZoomX cushioning for easy, everyday miles.", "price": 180.00, "category": "Running", "gender": "men", "color": "Black/White", "image_url": img(631986), "image_url_2": img(643471), "sizes": MEN_SIZES, "tags": ["running", "cushioned"], "sustainability_score": 76, "is_featured": False, "is_new": False},
    {"name": "Nike Wildhorse 8", "subtitle": "Men's Trail Shoes", "description": "Rock plate and aggressive lugs for rugged off-road adventures.", "price": 140.00, "category": "Trail", "gender": "men", "color": "Khaki/Orange", "image_url": img(643471), "image_url_2": img(2529148), "sizes": MEN_SIZES, "tags": ["trail"], "sustainability_score": 84, "is_featured": False, "is_new": True},
    {"name": "Nike Giannis Immortality 3", "subtitle": "Men's Basketball Shoes", "description": "Explosive cushioning for players who attack the rim.", "price": 90.00, "category": "Basketball", "gender": "men", "color": "Greek Freak", "image_url": img(1032110), "image_url_2": img(2529156), "sizes": MEN_SIZES, "tags": ["basketball"], "sustainability_score": 63, "is_featured": False, "is_new": False, "is_on_sale": True, "sale_price": 69.00},
    {"name": "Nike Dunk Low Kids", "subtitle": "Kids' Shoes", "description": "The street icon sized for young sneakerheads.", "price": 85.00, "category": "Lifestyle", "gender": "kids", "color": "Panda", "image_url": img(2529118), "image_url_2": img(267301), "sizes": KIDS_SIZES, "tags": ["kids", "dunk"], "sustainability_score": 73, "is_featured": True, "is_new": True},
    {"name": "Nike Vomero 17", "subtitle": "Women's Running Shoes", "description": "Plush ZoomX and ReactX foam for max cushioning on long runs.", "price": 150.00, "category": "Running", "gender": "women", "color": "Phantom/Volt", "image_url": img(298845), "image_url_2": img(1478442), "sizes": WOMEN_SIZES, "tags": ["running"], "sustainability_score": 77, "is_featured": False, "is_new": True},
    {"name": "Nike Motiva", "subtitle": "Women's Walking Shoes", "description": "Comfort rocker and plush foam for all-day walking comfort.", "price": 120.00, "category": "Lifestyle", "gender": "women", "color": "Iron Grey", "image_url": img(336372), "image_url_2": img(298845), "sizes": WOMEN_SIZES, "tags": ["walking", "comfort"], "sustainability_score": 79, "is_featured": False, "is_new": False},
    {"name": "Nike Air More Uptempo", "subtitle": "Men's Shoes", "description": "Bold AIR branding and full-length visible Air cushioning.", "price": 170.00, "category": "Lifestyle", "gender": "men", "color": "White/Black", "image_url": img(2529148), "image_url_2": img(1456706), "sizes": MEN_SIZES, "tags": ["90s", "iconic"], "sustainability_score": 50, "is_featured": False, "is_new": False, "is_on_sale": True, "sale_price": 129.00},
]
